#pragma once

enum class FIREARM_TYPE{
    SIG_M17,
    AR15,
    REMINGTON_700,
    RUGER_MK_IV,
    BENELLI_M4,
    __COUNT,
};

enum class CARTRIDGE_TYPE{
    CARTRIDGE_9MM,
    CARTRIDGE_223_REMINGTON,
    CARTRIDGE_30_06,
    CARTRIDGE_22LR,
    CARTRIDGE_12GA_BUCKSHOT,
    CARTRIDGE_12GA_SLUG,
    __COUNT,
};

enum class AMMO_TYPE{
    STANDARD_BULLET,
    HOLLOW_POINT,
    PELLET_SPREAD,
    RIFLED_SLUG,
};

enum class RELOAD_TYPE{
    DETACHABLE_MAGAZINE,
    DIRECT_LOAD,
};

enum class EXPLOSIVE_TYPE{
    M67_GRENADE,
    M18A1_CLAYMORE,
    M16_MINE,
    __COUNT,
};
